modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="MIT"


[[mods]] #mandatory
modId="effectblacklist" #mandatoryR
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://modrinth.com/project/effect-black-list" #optional
issueTrackerURL="https://github.com/1foxy2/effectblacklist/issues" #optional
#credits="" #optional
logoFile="icon.png" #optional
authors="${mod_author}" #optional
description='''${description}'''

[modproperties.modmenu]
sources="https://github.com/1foxy2/effectblacklist"

[[dependencies.effectblacklist]] #optional
    modId="forge" #mandatory
    type="required" #mandatory
mandatory = true
    versionRange="${neoforge_loader_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.effectblacklist]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
mandatory = true
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
